---
title: " Aim 1: Weather Data"
author: "Ben Burgunder"
date: today
date-format: "MMM D, YYYY"

editor: source

format:
  html:
    title-block-banner: true
    toc: true
    toc-depth: 6
    toc-float: true
    code-overflow: wrap
    code-fold: true
    theme: flatly
    
bibliography: grateful-refs.bib

fig-width: 8
fig-height: 7
---

### Loading Packages

```{r}
#| label: load_packages and set theme
#| message: false
#| warning: false

if (!require(pacman)) install.packages("pacman")
pacman::p_load(cowplot,
               here, 
               flextable,
               ggbump,
               ggrepel,
               ggdark,
               grateful,
               lubridate,
               lmtest, ggpubr, aod, lme4,
               magick,
               magrittr,
               flextable,
               patchwork,
               scales,
               tidyverse, 
               usmap,
               update = FALSE)

theme_set(theme_bw())


my_custom_theme <- function() {
  theme(legend.key.size = unit(2, 'cm'), #change legend key size
        legend.box.background = element_rect(color="white", size=2),
        legend.key.height = unit(1.01, 'cm'), #change legend key height
        legend.key.width = unit(0.8, 'cm'), #change legend key width
        legend.title = element_text(size=20, face="bold"), #change legend title font size
        legend.text = element_text(size=15),
        plot.title = element_text(size=30),
        axis.title = element_text(size=22),
        axis.text = element_text(size = 18))
  }

# cite_packages(omit = c("ggsn","ggthemes", "Unicode"),out.dir = ".")


```

### Reading in Data

```{r}
#| label: Read_Data
#| message: false
#| warning: false

OHare2021<-read.csv(here::here("Thesis_Projects", "CSVs","2021_SD_normals_OHare.csv"))
OHare2022<-read.csv(here::here("Thesis_Projects", "CSVs", "2022_SD_normalsOHare.csv"))




```

### Wrangling Data

```{r}
#| label: Wrangling
#| message: false
#| warning: false

appended2yrs<-rbind(OHare2021,OHare2022)

 WrangledOHare<-appended2yrs %>% 
   dplyr::mutate(.date=lubridate::mdy(Date),
                .year=lubridate::year(.date),
                .month=lubridate::month(.date),
                .woy=week(.date),
                .day=day(.date),
                .doy=yday(.date))%>% 
  dplyr::mutate(MNfactor= factor(month.abb[.month], levels = c("Jan", "Feb", "Mar", "Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))) %>% 
   dplyr::select(Maximum.Temperature,Minimum.Temperature,Normal.Max,Normal.Min,.doy, .woy,.date,.month,.year,.day,MNfactor)


```
### Graphing GDD's (need 230 at base 50)

```{r}
#| label: Graphing GDDs
#| message: false
#| warning: false
attach(WrangledOHare)
GDD_2021<-WrangledOHare %>% 
  filter(MNfactor%in%c("May","Jun"),
         .year=="2021") %>% 
  mutate(GDD=((Maximum.Temperature+Minimum.Temperature)/2)-50,
         Cumu_GDD=cumsum(GDD))

GDD_2022<-WrangledOHare %>% 
  filter(MNfactor%in%c("May","Jun"),
         .year=="2022") %>% 
  mutate(GDD=((Maximum.Temperature+Minimum.Temperature)/2)-50,
         Cumu_GDD=cumsum(GDD))

GDD_2yrs=rbind(GDD_2021,GDD_2022)

GDD2yrsGraph<-GDD_2yrs %>% 
  filter(Maximum.Temperature !="M") %>% 
  mutate(Maximum.Temperature=as.numeric(Maximum.Temperature),
         .year=as.character(.year)) %>%
  ggplot(aes(x=.doy, y=Cumu_GDD, color=.year, group=.year)) +
  # geom_bump(linewidth=1,smooth=8)+ 
  geom_line(linewidth=1.5)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 10)+
  my_custom_theme()+
  labs(title="", color="Year",x="Day of the Year", y="GDD Accumulation")+
  coord_cartesian(ylim=c(0,1100))

GDD2yrsGraph

ggsave(here::here("Thesis_Projects", "Figures", "GDD_2yrs.png"),  width = 12, height = 8, dpi = 300)



```
### Analysis
```{r}
#| label: Analysis

earlyszn<-GDD_2yrs %>% filter(.doy<160)

# Perform t-test
t_test_result <- t.test(Cumu_GDD ~ .year, data = earlyszn)

# Print t-test result
print(t_test_result)

qqnorm(earlyszn$Cumu_GDD)


# Perform Shapiro-Wilk test
shapiro_test_result <- shapiro.test(GDD_2yrs$Cumu_GDD)

# Print the result
print(shapiro_test_result)

wilcox.test(Cumu_GDD ~ .year, data = GDD_2yrs)




```






### Graphing Max Weekly temp of both years against avg temp

```{r}
#| label: Graphing
#| message: false
#| warning: false


TwoYearsWOY_max<-WrangledOHare %>% 
  filter(Maximum.Temperature !="M") %>% 
  mutate(Maximum.Temperature=as.numeric(Maximum.Temperature),
         .year=as.character(.year)) %>%
  group_by(.woy,.year) %>% 
  summarise(Week_avg=mean(Maximum.Temperature)) %>% 
  ggplot(aes(x=.woy, y=Week_avg, color=.year, group=.year)) +
  # geom_bump(linewidth=1,smooth=8)+ 
  geom_line(linewidth=1)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 20)+
  labs(title="Weekly Temp: Chicago's O'Hare Airport", color="Year",x="Week of the Year", y="Max Temp (°F)")+
  coord_cartesian(xlim=c(18,27),ylim=c(45,90))

```
### Graphing Max Daily temp of both years against avg temp

```{r}

TwoYearsDOY_max<-WrangledOHare %>% 
  filter(Maximum.Temperature !="M") %>% 
  mutate(Maximum.Temperature=as.numeric(Maximum.Temperature),
         .year=as.character(.year)) %>% 
  ggplot(aes(x=.doy, y=Maximum.Temperature, color=.year, group=.year)) +
  geom_bump(linewidth=1,smooth=8)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 20)+
  labs(title="Daily Temp: Chicago's O'Hare Airport", color="Year",x="Day of the Year", y="Max Temp (°F)")+
  coord_cartesian(xlim=c(60,151))

TwoYearsDOY_min<-WrangledOHare %>% 
  filter(Minimum.Temperature !="M") %>% 
  mutate(Minimum.Temperature=as.numeric(Minimum.Temperature),
         .year=as.character(.year)) %>% 
  ggplot(aes(x=.doy, y=Minimum.Temperature, color=.year, group=.year)) +
  geom_bump(linewidth=1,smooth=8)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 20)+
  labs(title="Daily Temp: Chicago's O'Hare Airport", color="Year",x="Day of the Year", y="Min Temp (°F)")+
  coord_cartesian(xlim=c(60,151))


ggsave(here::here("Aim1Code", "Figures", "ILWeather.png"),  width = 12, height = 7, dpi = 300)


Diff_from_Normal_max<-WrangledOHare %>% 
  filter(Maximum.Temperature !="M") %>% 
  mutate(Maximum.Temperature=as.numeric(Maximum.Temperature),
         .year=as.character(.year),
         diff=Maximum.Temperature-Normal.Max) %>% 
  ggplot(aes(x=.doy, y=diff, color=.year, group=.year)) +
  geom_bump(linewidth=1,smooth=8)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 20)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  labs(title="Departure from Historical Avg Daily Temp: Chicago's O'Hare Airport", color="Year",x="Day of the Year", y="Departure from Avg Max Temp (°F)")+
  coord_cartesian(xlim=c(60,151))

Diff_from_Normal_min<-WrangledOHare %>% 
  filter(Minimum.Temperature !="M") %>% 
  mutate(Minimum.Temperature=as.numeric(Minimum.Temperature),
         .year=as.character(.year),
         diff=Minimum.Temperature-Normal.Min) %>% 
  ggplot(aes(x=.doy, y=diff, color=.year, group=.year)) +
  geom_bump(linewidth=1,smooth=8)+ 
  scale_color_manual(values = c("#B3DDF2", "#FF0000")) +
  scale_x_continuous(n.breaks = 10)+
  scale_y_continuous(n.breaks = 20)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  labs(title="Departure from Historical Avg Daily Temp: Chicago's O'Hare Airport", color="Year",x="Day of the Year", y="Departure from Avg Min Temp (°F)")+
  coord_cartesian(xlim=c(60,151))

ggsave(here::here("Thesis_Projects", "Figures", "DiffedILWeather.png"),  width = 12, height = 7, dpi = 300)



```

```{r}
# Filter data for days 60 to 151
filtered_data <- WrangledOHare %>%
  filter(.doy >= 60 & .doy <= 151) %>% 
  group_by(.year) %>% 
  summarize(Avg=mean(Minimum.Temperature))


#May and June Table
tabledmaxmin<-WrangledOHare %>% 
  filter(MNfactor%in%c("May","Jun")) %>% 
  group_by(.year) %>% 
  summarize(
    Max=mean(Maximum.Temperature),
    Min=mean(Minimum.Temperature))


```





