---
title: "Thesis Inconsistent Pool Size RLS"
author: "Ben Burgunder"
date: today
date-format: "MMM D, YYYY"

editor: source

format:
  html:
    title-block-banner: true
    toc: true
    toc-depth: 6
    toc-float: true
    code-overflow: wrap
    code-fold: true
    theme: flatly
    
bibliography: grateful-refs.bib

fig-width: 8
fig-height: 7
---

### Loading Packages

```{r}
#| label: load_packages and set theme
#| message: false
#| warning: false

if (!require(pacman)) install.packages("pacman")
pacman::p_load(binGroup,
               cowplot,
               here, 
               flextable,
               ggrepel,
               ggdark,
               ggmap,
               grateful,
               lubridate,
               fitdistrplus,
               ggpubr,
               magick,
               magrittr,
               mass,
               flextable,
               forcats,
               patchwork,
               scales,
               tidyverse, 
               usmap,
               update = FALSE)

theme_set(theme_bw())

my_custom_theme <- function() {
  theme(legend.key.size = unit(2, 'cm'), #change legend key size
        legend.box.background = element_rect(color="white", size=2),
        legend.key.height = unit(1.01, 'cm'), #change legend key height
        legend.key.width = unit(0.8, 'cm'), #change legend key width
        legend.title = element_text(size=20, face="bold"), #change legend title font size
        legend.text = element_text(size=15),
        # legend.background = element_rect(color="black", size=.5, linetype="dotted"),
        plot.title = element_text(size=30),
        strip.text = element_text(size=18),
        axis.title = element_text(size=22),
        axis.text = element_text(size = 18))
  }
```

### Reading in Data

```{r}
#| label: Read_Data
#| message: false
#| warning: false


MergeLongways2<-read.csv(here::here("Thesis_Projects","CSVs", "IPS_MergeLongways.csv")) %>% 
  rename(Hex=Hex.x,
         Category=Category.x)
```



###By Category
```{r}
GenericPos_MLW2<-MergeLongways2 %>% 
  filter(Month=="RJ",Category=="Equal")
GenericPos_MLW2
Generic_testResult<- GenericPos_MLW2$positive
Generic_poolSize<- GenericPos_MLW2$CountMosq
Generic_mle = pooledBin(Generic_testResult,Generic_poolSize,pt.method = "mle",ci.method="bc-skew-score",scale = 1000)
Generic_mle
```



###Yearless
```{r}
#PJ
MergeLongways11<-MergeLongways2 %>% 
  filter(Month=="PJ")
testResult11<- MergeLongways11$positive
poolSize11<- MergeLongways11$CountMosq
mle11 = pooledBin(testResult11,poolSize11,pt.method = "mle",ci.method="skew-score",scale = 1000)

#PA
MergeLongways12<-MergeLongways2 %>% 
  filter(Month=="PA")
testResult12<- MergeLongways12$positive
poolSize12<- MergeLongways12$CountMosq
mle12 = pooledBin(testResult12,poolSize12,pt.method = "mle",ci.method="skew-score",scale = 1000)   

#RJ
MergeLongways13<-MergeLongways2 %>% 
  filter(Month=="RJ")
testResult13<- MergeLongways13$positive
poolSize13<- MergeLongways13$CountMosq
mle13 = pooledBin(testResult13,poolSize13,pt.method = "mle",ci.method="skew-score",scale = 1000)    


#RA
MergeLongways14<-MergeLongways2 %>% 
  filter(Month=="RA")
testResult14<- MergeLongways14$positive
poolSize14<- MergeLongways14$CountMosq
mle14 = pooledBin(testResult14,poolSize14,pt.method = "mle", ci.method="skew-score",scale = 1000) 

mle11
mle12
mle13
mle14
```

###IPS Graphing No Cats
```{r}
IPS_Yearless<-read.csv(here::here("Thesis_Projects","CSVs", "Yearless_IPS.csv"))

IPS_Graph<-IPS_Yearless %>% 
  filter(CI=="bsc") %>% 
  mutate(Species = case_when(
    Species == "R" ~ "Cx. restuans", 
    Species == "P" ~ "Cx. pipiens"),
    Month=case_when(
    Month=="J"~"July",
    Month=="A"~"August")) %>% 
    mutate(Month = factor(Month, levels = month.name)) %>% 
  ggplot(aes(
    x = Species,
    y = PointEst,
    fill = Species,
  )) +
  # facet_grid(Year~Month,space="free")+
  facet_wrap(~Month)+
  geom_bar(color = "black",alpha = 0.3, stat="identity") +
  geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0.2, color = "black", linewidth = 1) +  # Confidence intervals
  scale_fill_manual(values = c("lightgoldenrod", "cadetblue2")) +
  # geom_jitter(aes(fill=Species),size=3, shape=21,color="black") +
   scale_x_discrete(labels = expression(italic("Cx. pipiens"), italic("Cx. restuans"))) +
   my_custom_theme()+
  theme(legend.position = 'none',
        plot.title = element_text(size=22))+
     # coord_cartesian(ylim = c(0,200))+
  labs(fill="Category",x="Species", y="Infection Rate (MLE)", title=""
       #title=expression(paste("Surveyed ",italic("Culex "), "Infection Rate, Extreme Outliers (MIR > 200) Not Shown" ))
       )
IPS_Graph

ggsave(here::here("Thesis_Projects", "Figures", "IPS_Yearless.png"),  width = 12, height = 7, dpi = 300)

```


###IPS Graphing with Cats
```{r}
IPS_Categorized<-read.csv(here::here("Thesis_Projects","CSVs", "Categorized_binGroup.csv"))

# IPS_Categorized$Category_fac=factor(IPS_Categorized$Category, levels=c('Lower','Equal', 'Higher'))


IPS_Graph_Categorized<-IPS_Categorized %>% 
  filter(CI=="bsc") %>% 
  mutate(Species = case_when(
    Species == "R" ~ "Cx. restuans", 
    Species == "P" ~ "Cx. pipiens"),
    Month=case_when(
    Month=="J"~"July",
    Month=="A"~"August"),
    Category=case_when(
      Category=="L"~"Lower",
      Category=="E"~"Equal",
      Category=="H"~"Higher",
    )) %>% 
    mutate(Month = factor(Month, levels = month.name),
           Category=factor(Category, levels=c("Lower","Equal","Higher"))) %>% 
  ggplot(aes(
    x = Species,
    y = PointEst,
    fill = Category,
  )) +
  facet_wrap(~Month)+
  # geom_bar(color = "black",alpha = 0.3, stat="identity", position="dodge") +
  # geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0.2, color = "black", linewidth = 1, position="dodge") +  # Confidence intervals
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), color="black",alpha=0.3) +  # Bars dodged
  geom_errorbar(aes(ymin = Lower, ymax = Upper), 
                position = position_dodge(width = 0.9),  # Error bars dodged
                width = 0.25) +
  
  scale_fill_manual(values = c("#25CED1", "#FF7F50", "#F8C537")) +
  scale_x_discrete(labels = expression(italic("Cx. pipiens"), italic("Cx. restuans"))) +
   my_custom_theme()+
  labs(fill="Category",x="Species", y="Infection Rate (MLE)", title=""
       #title=expression(paste("Surveyed ",italic("Culex "), "Infection Rate, Extreme Outliers (MIR > 200) Not Shown" ))
       )
IPS_Graph_Categorized

ggsave(here::here("Thesis_Projects", "Figures", "IPS_Categorized.png"),  width = 12, height = 7, dpi = 300)

```