---
title: "Thesis: Aim 2 Analysis"
author: "Ben Burgunder"
date: today
date-format: "MMM D, YYYY"

editor: source

format:
  html:
    title-block-banner: true
    toc: true
    toc-depth: 6
    toc-float: true
    code-overflow: wrap
    code-fold: true
    theme: flatly
    
bibliography: grateful-refs.bib

fig-width: 8
fig-height: 7
---

### Loading Packages

```{r}
#| label: load_packages and set theme
#| message: false
#| warning: false

if (!require(pacman)) install.packages("pacman")
pacman::p_load(cowplot,
               here, 
               flextable,
               ggrepel,
               ggdark,
               grateful,
               lubridate,
               ggpubr,
               lmtest,
               magick,
               magrittr,
               ggbump,
               mass,
               flextable,
               patchwork,
               scales,
               tidyverse, 
               usmap,
               update = FALSE)

theme_set(theme_bw())

my_custom_theme <- function() {
  theme(legend.key.size = unit(2, 'cm'), #change legend key size
        legend.box.background = element_rect(color="white", size=2),
        legend.key.height = unit(1.01, 'cm'), #change legend key height
        legend.key.width = unit(0.8, 'cm'), #change legend key width
        legend.title = element_text(size=20, face="bold"), #change legend title font size
        legend.text = element_text(size=15),
        # legend.background = element_rect(color="black", size=.5, linetype="dotted"),
        plot.title = element_text(size=30),
        strip.text = element_text(size=18),
        axis.title = element_text(size=22),
        axis.text = element_text(size = 18))
  }
```

#MosqLegs
```{r}
FullSampleList<-read.csv(here::here("Thesis_Projects","CSVs", "A2_ListofallMosqTested.csv"))



FSL_Summed<-FullSampleList %>% 
rename(Month=Month..7.8.,
       Species=Abdomen.Species.ID) %>% 
  mutate(Species = case_when(
    Species == "P" ~ "pipiens", 
    Species == "p" ~ "pipiens",
    Species=="R"~"restuans",
    Species=="r"~"restuans")) %>% 
    filter(!is.na(Legs)) %>% 
  mutate(Month = factor(Month, levels = month.name)) %>% 
 ggplot(aes(x = Legs, fill=Species)) +
  geom_histogram(binwidth = 1, alpha=0.8) +
  facet_grid(Year ~ Month) +  # Facet by year and month
  theme_minimal() +
  labs(title = "",
       x = "Legs per Mosquito",
       y = "Count")+
  scale_x_continuous(n.breaks=6)+
  scale_fill_discrete() +
  scale_fill_manual(values = c("lightgoldenrod", "cadetblue2"),
                    # labels = expression(italic("Cx. pipiens"), italic("Cx. restuans")),
                    labels=c("Cx. pipiens","Cx. restuans")
                    ) +
  theme_bw()+
  my_custom_theme()+
theme(legend.text = element_text(face = "italic"))

FSL_Summed

ggsave(here::here("Thesis_Projects", "Figures", "FSL_Summed.png"),  width = 12, height = 8, dpi = 300)

```

```{r}
#| label: Read_Data
#| message: false
#| warning: false

MIR_calc_all_analysis<-read.csv(here::here("Thesis_Projects","CSVs", "MIRcalcAll.csv"))

MIR_calc_all_analysis$Month_f=factor(MIR_calc_all_analysis$Month, levels=c('July','August'))
#Summary Info
NumPosvsTotals<-MIR_calc_all_analysis %>% 
  group_by(Species, Month_f) %>% 
  dplyr::summarize(Positive_Pools=sum(Positive),Total_Pools=sum(TotalSamples),Mosquitoes=sum(summed_MQ)) %>% 
  mutate(PropPools=Positive_Pools/Total_Pools) %>% 
  rename('Month Collected'=Month_f,
         'Positive Pools'=Positive_Pools,
         'Total Pools'=Total_Pools) 


```

### 2021 MIR Analysis
```{r}
#| label: 2021 Analysis
#| message: false
#| warning: false

# library(lme4)
# library(lmtest)
# attach(MIR_calc_all_analysis)

MIR_2021_Cleave<-MIR_calc_all_analysis

b2021_model_1<-glmer(cbind(Positive, TotalSamples - Positive) ~ Species * Month + Category + (1 | Hex) + (1 | Year),
               data = MIR_2021_Cleave,
               family = binomial)
AIC(b2021_model_1)
summary(b2021_model_1) #full model is good


b2021_model_2<-glmer(cbind(Positive, TotalSamples - Positive) ~ Species + Month + Category + (1 | Hex)+ (1 | Year),
               data = MIR_2021_Cleave,
               family = binomial)
AIC(b2021_model_2)
summary(b2021_model_2)
lrtest(b2021_model_2,b2021_model_1) #interaction was significant, AIC goes up w removal

b2021_model_3<-glmer(cbind(Positive, TotalSamples - Positive) ~ Species * Month + (1 | Hex)+ (1 | Year),
               data = MIR_2021_Cleave,
               family = binomial)
summary(b2021_model_3)
AIC(b2021_model_3)  #model 3 has the lowest AIC btw 1-4
lrtest(b2021_model_3,b2021_model_1) #interaction not significant, AIC goes down w removal

AIC(b2021_model_1,b2021_model_2,b2021_model_3)

```
###Probabilities
```{r}
#Probability of pip being infected in Aug
exp(-0.9875) #0.3725068
#Probability of pip being infected in Jul
exp(-0.9875+-0.5425) #0.2165357
#Probability of rest being infected in Aug
exp(-0.9875+-1.9611) #0.05241303
#Probability of rest being infected in Aug
exp(-0.9875+-1.9611+-0.5425+2.0668) #0.2406769
```

